cetool/urls.py
from django.urls import path

from ecp.views import EcpView

urlpatterns = [
    path('ecp/', EcpView.as_view()),
]

base/models.py
from django.db import models

# Create your models here.

ecp/models.py
from django.db import models

# Create your models here.

ecp/forms.py
import datetime
from django import forms

now = datetime.datetime.now()


class EcpForm(forms.Form):
    performer = forms.CharField(widget=forms.Textarea, label="Wykonawca")
    month = forms.IntegerField(min_value=1, max_value=12, label="Miesiąc", initial=now.month)
    year = forms.IntegerField(min_value=2017, label="Rok", initial=now.year)
    hours_sum = forms.IntegerField(min_value=0, label="Suma godzin", initial=0)
    hourly_bid = forms.IntegerField(min_value=0, label="Stawka godz", initial=50)
    sum = forms.IntegerField(min_value=0, label="Suma zł", initial=0)

    def __init__(self, *args, **kwargs):
        super(EcpForm, self).__init__(*args, **kwargs)
        counter = 1
        for q in range(1, 32):
            self.fields['day-' + str(counter)] = forms.CharField(label="Dzień {}".format(q), initial=0, required=False)
            self.fields['desc-' + str(counter)] = forms.CharField(label="Opis {}".format(q), initial="", required=False)
            counter += 1

base/views.py
from django.shortcuts import render

# Create your views here.

ecp/views.py
from django.http import HttpResponse
from django.views.generic.edit import FormView

from ecp.forms import EcpForm
from ecp.pdf import build_pdf


class EcpView(FormView):
    template_name = 'ecp.html'
    form_class = EcpForm
    success_url = '/ecp/'

    def form_invalid(self, form):
        print("invalid")
        print(form.errors)
        return super().form_invalid(form)

    def form_valid(self, form):
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="ecp-{}-{}.pdf"'.format(form.cleaned_data['month'],
                                                                                        form.cleaned_data['year'])
        build_pdf(form, response)
        return response

        # return super().form_valid(form)

base/templates/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{page_title}}</title>

    {% bootstrap_css %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    {% bootstrap_javascript %}

    {% block head %}{% endblock %}
</head>
<body>


 <!--<nav class="navbar navbar-expand-lg navbar-light bg-light">-->
  <!--<a class="navbar-brand" href="#"></a>-->
  <!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">-->
    <!--<span class="navbar-toggler-icon"></span>-->
  <!--</button>-->
  <!--<div class="collapse navbar-collapse" id="navbarNav">-->
    <!--<ul class="navbar-nav">-->
      <!--<li class="nav-item active">-->
        <!--<a class="nav-link" href="/">Start <span class="sr-only">(current)</span></a>-->
      <!--</li>-->
      <!--<li class="nav-item">-->
        <!--<a class="nav-link" href="/ecp/">ECP</a>-->
      <!--</li>-->
    <!--</ul>-->
  <!--</div>-->
<!--</nav>-->

<main class="container-fluid">
    {% bootstrap_messages %}

    {% block content %}

    {% endblock %}
</main>
</body>
</html>

ecp/templates/ecp.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

<h1>
    Ewidencja czasu pracy
</h1>

<hr/>

<form action="/ecp/" method="post">{% csrf_token %}

    <div class="row">
        <div class="col-md-5">
            {% bootstrap_field form.performer size='small' %}
        </div>
        <div class="col-md-7">
            <div class="row">
                <div class="col-sm-6">
                    {% bootstrap_field form.year %}
                </div>
                <div class="col-sm-6">
                    {% bootstrap_field form.month %}
                </div>
            </div>

            <div class="row">
                <div class="col-sm-4">
                    {% bootstrap_field form.hours_sum %}
                </div>
                <div class="col-sm-4">
                    {% bootstrap_field form.hourly_bid %}
                </div>
                <div class="col-sm-4">
                    {% bootstrap_field form.sum %}
                </div>
            </div>
        </div>
    </div>

    <div id="days">

    </div>

    <input type="submit" value="Generuj PDF" class="btn btn-success btn-block"/>
</form>

<script type="text/javascript">

// these are labels for the days of the week
cal_days_labels = ['Pon', 'Wt', 'Śr', 'Czw', 'Pt', 'So', 'Ndz'];

// these are the days of the week for each month, in order
cal_days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];


function create_calendar(){

    month = $('#id_month').val()-1;
    year = $('#id_year').val();

    recalculate();

  // get first day of month
  var firstDay = new Date(year, month, 1);
  var startingDay = (firstDay.getDay() || 7) -1;
  console.info({
    'f': startingDay,
    'month': month,
    'year': year
  });

  // find number of days in month
  var monthLength = cal_days_in_month[month];

  // compensate for leap year
  if (month == 1) { // February only!
    if((year % 4 == 0 && year % 100 != 0) || year % 400 == 0){
      monthLength = 29;
    }
  }

  // do the header
  var html = '<table class="calendar-table table table-bordered">';
  html += '<thead><tr class="calendar-header">';
  for(var i = 0; i <= 6; i++ ){
    html += '<th class="calendar-header-day" width="14.28%">';
    html += cal_days_labels[i];
    html += '</th>';
  }
  html += '</tr></thead><tr>';

  // fill in the days
  var day = 1;
  // this loop is for is weeks (rows)
  for (var i = 0; i < 9; i++) {
    // this loop is for weekdays (cells)
    for (var j = 0; j <= 6; j++) {
      html += '<td class="calendar-day">';
      if (day <= monthLength && (i > 0 || j >= startingDay)) {

        html += '<div class="row">';
        html += '<div class="col-md-3 text-right">dzień:</div><div class="col-md-3"><input type="text" value="'+day+'" readonly="readonly"></div>';
        html += '<div class="col-md-3 text-right">godzin:</div><div class="col-md-3"><input class="h" type="text" name="day-' + day + '" value="0"></div>';
        html += '</div>';

        html += '<textarea name="desc-' + day + '" placeholder="Opis"></textarea>';

        day++;
      }
      html += '</td>';
    }
    // stop making rows if we've run out of days
    if (day > monthLength) {
      break;
    } else {
      html += '</tr><tr>';
    }
  }
  html += '</tr></table>';

  $('#days').html( html );
}

function recalculate() {
    $('#id_hours_sum').val(0);
    $('#id_sum').val(0);

    var sum = 0;
    $('.calendar-table input.h').each(function(){
        sum += parseFloat($(this).val());
    });

     $('#id_hours_sum').val(sum);
     $('#id_sum').val(sum * parseFloat($('#id_hourly_bid').val()));
}

$('body').on('change', '.calendar-table input', recalculate)
$('#id_hourly_bid').change(recalculate);
$('#id_month').change(create_calendar);
$('#id_year').change(create_calendar);

create_calendar();





</script>


{% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'ecp.css' %}"/>
{% endblock %}